nelmio_api_doc:
    documentation:
        info:
            title: API de Restaurantes
            description: Documentación de la API para gestión de restaurantes
            version: 1.0.0
    areas:
        default:
            path_patterns: [ ^/api ]
