nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['*']
    allow_headers: ['Content-Type', 'X-AUTH-TOKEN']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['Content-Type', 'X-AUTH-TOKEN']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
