security:
    providers:
        app_user_provider:
            memory:
                users:
                    api-user:
                        password: ''
                        roles: ['ROLE_API']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator

    access_control:
        - { path: ^/api, roles: ROLE_API }
